#!/bin/bash

echo "##########################################################################"
echo "gdal" $VERSION
echo "##########################################################################"

LINUX_DISTRIBUTION="$DIST_NAME$DIST_VERSION"

mkdir -p $BUILD_DIR
cd $BUILD_DIR

# If Docker rootless, ensure that user can read them
if [ -f /.dockerenv ]; then
    find $BUILD_DIR -type f -exec chmod u+rwx {} \;
fi

CMAKE_OPTIONS=

if [ -n "$SAT_HPC" ]  && [ -n "$MPI_ROOT_DIR" ]; then
   echo "WARNING: setting CC and CXX environment variables and target MPI wrapper"
   CMAKE_OPTIONS+=" -DCMAKE_CXX_COMPILER:STRING=${MPI_CXX_COMPILER}"
   CMAKE_OPTIONS+=" -DCMAKE_C_COMPILER:STRING=${MPI_C_COMPILER}"
fi

CMAKE_OPTIONS+=" -DCMAKE_BUILD_TYPE=Release"
CMAKE_OPTIONS+=" -DCMAKE_INSTALL_PREFIX:STRING=${PRODUCT_INSTALL}"
CMAKE_OPTIONS+=" -DCMAKE_INSTALL_LIBDIR:STRING=lib"
CMAKE_OPTIONS+=" -DCMAKE_INSTALL_NAME_DIR:PATH=${PRODUCT_INSTALL}/lib"
CMAKE_OPTIONS+=" -DGDAL_USE_EXTERNAL_LIBS:BOOL=OFF"
CMAKE_OPTIONS+=" -DGDAL_USE_INTERNAL_LIBS:BOOL=OFF" # internal ON is OK, but recompiled ZLIB
CMAKE_OPTIONS+=" -DGDAL_USE_CURL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_LIBXML2:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_EXPAT:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_ZLIB:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_HDF5:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_ICONV:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_OPENSSL:BOOL=ON" #${openssl_enabled}"
CMAKE_OPTIONS+=" -DGDAL_USE_SQLITE3:BOOL=ON" #${sqlite_enabled}"
CMAKE_OPTIONS+=" -DGDAL_BUILD_OPTIONAL_DRIVERS:BOOL=OFF"
CMAKE_OPTIONS+=" -DGDAL_ENABLE_DRIVER_HDF5:BOOL=ON"
CMAKE_OPTIONS+=" -DOGR_ENABLE_DRIVER_DGN:BOOL=OFF"
CMAKE_OPTIONS+=" -DOGR_ENABLE_DRIVER_IDRISI:BOOL=OFF"
CMAKE_OPTIONS+=" -DOGR_ENABLE_DRIVER_SDTS:BOOL=OFF"
CMAKE_OPTIONS+=" -DOGR_ENABLE_DRIVER_S57:BOOL=OFF"
CMAKE_OPTIONS+=" -DBUILD_APPS:BOOL=OFF"
CMAKE_OPTIONS+=" -DBUILD_CSHARP_BINDINGS:BOOL=OFF"
CMAKE_OPTIONS+=" -DBUILD_JAVA_BINDINGS:BOOL=OFF"
CMAKE_OPTIONS+=" -DBUILD_PYTHON_BINDINGS:BOOL=ON"
CMAKE_OPTIONS+=" -DBUILD_TESTING:BOOL=OFF"
CMAKE_OPTIONS+=" -DCMAKE_INSTALL_RPATH:STRING=${PRODUCT_INSTALL}/lib"

if [  $LINUX_DISTRIBUTION == "CO7" ]; then
    CMAKE_OPTIONS+=" -DGDAL_USE_ZSTD:BOOL=OFF" #FIXME
else
    CMAKE_OPTIONS+=" -DGDAL_USE_ZSTD:BOOL=ON"
fi

CMAKE_OPTIONS+=" -DGDAL_USE_PCRE2:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_GEOS:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_NETCDF:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_LIBLZMA:BOOL=ON"

CMAKE_OPTIONS+=" -DGDAL_USE_GEOTIFF_INTERNAL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_JPEG_INTERNAL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_PNG_INTERNAL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_TIFF_INTERNAL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_GIF_INTERNAL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_JSONC_INTERNAL:BOOL=ON"
CMAKE_OPTIONS+=" -DGDAL_USE_BLOSC_INTERNAL:BOOL=ON"

if [ $LINUX_DISTRIBUTION == "FD40" ]; then
    CMAKE_OPTIONS+=" -DCMAKE_CXX_FLAGS=-fpermissive"
fi

echo
echo "*** cmake $CMAKE_OPTIONS $SOURCE_DIR"
cmake $CMAKE_OPTIONS $SOURCE_DIR
if [ $? -ne 0 ]
then
    echo "ERROR on cmake"
    exit 1
fi

echo
echo "*** make $MAKE_OPTIONS"
make $MAKE_OPTIONS
if [ $? -ne 0 ]
then
    echo "ERROR on make"
    exit 2
fi

echo
echo "*** make install"
make install
if [ $? -ne 0 ]
then
    echo "ERROR on make install"
    exit 3
fi

echo
echo "########## END"

